### ISSUE TITLE
GetTypeOf() shows an error in Eclipse

### ISSUE THREAD

**Issue by schmidtze-berlin** [detky/PowerArray#1]
In Eclipse (Mars) the "return pa.utils.DataTypes.function" in GetTypeOf() (currently in line 154) will be marked as an error as it uses the keyword "function". The exact message is

  Syntax error on token "function", Identifier expected

Many thanks for PA and best regards
Friedemann ;-)

**Comment by detky** [comment]
Solved with commit 0cd9ecfc2ad3e8b9beedf4ce34bb490d548757e8.

Thank you!!!!
