### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by markusressel** [detky/PowerArray#2]
Hey there,
sweet little library but I have a problem when trying to sort an array:

```
PowerArray.js?7f5d:1100 Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at Array.Sort (PowerArray.js?7f5d:1100)
    at eval (main.js?2ee2:61)
    at Module../src/main.js (app.js:3985)
    at __webpack_require__ (app.js:725)
    at fn (app.js:102)
    at Object.0 (app.js:4010)
    at __webpack_require__ (app.js:725)
    at app.js:792
    at app.js:795
```

Simple example:
```
import "./libraries/PowerArray.js"

let o1 = {
    name: "Z"
};
let o2 = {
    name: "A"
};

let test = [o1, o2];
let sortedTest = test.Sort({name: Sort.Ascendig});
```

Since there are no releases in this repo I just used the last available `PowerArray.js` file from `master` branch. Any idea how to fix this?

**Comment by detky** [comment]
Hi Markus,
I can't see any error in your code. I'll take a look tonight. Probably it's
an already solved problem and the published version is a bit old. You'll
hear from me.

Regards
Sebastian

Markus Ressel <notifications@github.com> schrieb am Di., 14. Aug. 2018,
13:54:

**Comment by detky** [comment]
Markus, I didn't make any test jet, but try to require the library instead
of importing it, and please let me know if something changes


Regards,
Sebastian

Markus Ressel <notifications@github.com> schrieb am Di., 14. Aug. 2018,
13:54:

**Comment by markusressel** [comment]
```
require("./libraries/PowerArray.js")

 let o1 = {
     name: "Z"
 };
 let o2 = {
     name: "A"
 };

 let test = [o1, o2];
 let sortedTest = test.Sort({name: Sort.Ascendig});
```

gives the same error.

**Comment by detky** [comment]
Hi Markus,

i found a typo in your code:

test.Sort({name: Sort.Ascendi*N*g});


the N was missing :)


Regards,
Sebastian


Markus Ressel <notifications@github.com> schrieb am Di., 14. Aug. 2018,
13:54:

**Comment by markusressel** [comment]
Oh my... it works as is should now.
Although this was a pretty silly mistake on my end the error message is quite misleading.

Thx for your very fast help!
